### ISSUE TITLE
Deprecate/remove AdoptOpenJDK hotspot

### ISSUE THREAD

**Issue by jorsol** [eddumelendez/sdkman-java-migrations#11]
Now that Eclipse Temurin has the first release, it should be considered to drop the hotspot releases from AdoptOpenJDK.

**Comment by eddumelendez** [comment]
Hi @jorsol, thank you so much for raising an issue. We will be hiding adoptopenjdk once IBM Semeru releases the macos binaries.

I will leave the issue open until that happen.

**Comment by abcfy2** [comment]
Hi @eddumelendez , now IBM Semeru already releases the macos binaries: https://developer.ibm.com/languages/java/semeru-runtimes/downloads?os=macOS

**Comment by eddumelendez** [comment]
No more versions are submitted under adoptopenjdk. They are available in sdkman but hidden.

The project is going to be archive at some point. For future reference looks at [this](https://github.com/sdkman/sdkman-disco-migration) which contains support for more vendors.
